name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore MyMoney.Api.WebApi.sln
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test MyMoney.Api.WebApi.sln
